const state = {
    autoDialValue: 0,
    user: null,
    token: "",
    onCall: false,
    campaign: null,
    status: null,
    dispositionModal: false,
    successModal: false,
    errorModal: false,
    infoModal: false,
    //paused: true,
    campaigns: [],
    Phonenumber: null,
    selectedIngroups: [],
    ingroups: [],
    callType: "Outgoing",
    callStatus: "",
    dispositionOptions: [],
    codeOptions: [],
    pauseCode: "LoggedIn",
    pauseafterCall: "",
    numberCalled: null,
    hangupError: false,
    hangupReason: "",
    callWaiting: true,
    ongoingCall: false,
    TransferCall: false,
    callQueue: [],

    transfer: "",
    transferedCall: false,

    dtmfTrue: false,

    errorTitle: "Dynamic Error Title",
    errorText:
        "Dynamic Error Body Dynamic Error Body Dynamic Error Body Dynamic Error BodyDynamic Error BodyDynamic Error Bodyv v ",
    activeUsers: [],
    liveTransferred: false,
    addedNumber: null,
    grabTrue: false,

    userState: "",
    socket: null,
    dialable_leads: 0,
    callLogs: [],
    activeAgents: [],
    callbacks: [],
    pause_code: null,
    agent_log_id: null,
    dial_method: null,
    iframe: "http://172.16.10.202/login",
};

export default state